### ISSUE TITLE
modoboa-amavis: Relation "msgrcpt" does not exist

### ISSUE THREAD

**Issue by ohidxy** [modoboa/modoboa-amavis#104]
ProgrammingError at /dashboard/

relation "msgrcpt" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "msgrcpt" WHERE "msgrcpt"....

I have two separate postgres DB for modoboa and amavis. 
```python
Traceback:

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

The above exception (relation "msgrcpt" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "msgrcpt" WHERE "msgrcpt"....
                                          ^
) was the direct cause of the following exception:

File "/srv/modoboa/env/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  215.                 response = response.render()

File "/srv/modoboa/env/lib/python3.5/site-packages/django/template/response.py" in render
  107.             self.content = self.rendered_content

File "/srv/modoboa/env/lib/python3.5/site-packages/django/template/response.py" in rendered_content
  84.         content = template.render(context, self._request)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/template/backends/django.py" in render
  66.             return self.template.render(context)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/template/base.py" in render
  205.                 with context.bind_template(self):

File "/usr/lib/python3.5/contextlib.py" in __enter__
  59.             return next(self.gen)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/template/context.py" in bind_template
  263.             updates.update(processor(self.request))

File "/srv/modoboa/env/lib/python3.5/site-packages/modoboa/core/context_processors.py" in top_notifications
  19.         sender="top_notifications", include_all=False)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/dispatch/dispatcher.py" in send
  193.             for receiver in self._live_receivers(sender)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/dispatch/dispatcher.py" in <listcomp>
  193.             for receiver in self._live_receivers(sender)

File "/srv/modoboa/env/lib/python3.5/site-packages/modoboa_amavis/handlers.py" in check_for_pending_requests
  166.     nbrequests = SQLconnector(user=request.user).get_pending_requests()

File "/srv/modoboa/env/lib/python3.5/site-packages/modoboa_amavis/sql_connector.py" in get_pending_requests
  233.         return Msgrcpt.objects.filter(rq).count()

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/models/query.py" in count
  364.         return self.query.get_count(using=self.db)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/models/sql/query.py" in get_count
  499.         number = obj.get_aggregation(using, ['__count'])['__count']

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/models/sql/query.py" in get_aggregation
  480.         result = compiler.execute_sql(SINGLE)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/models/sql/compiler.py" in execute_sql
  899.             raise original_exception

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/models/sql/compiler.py" in execute_sql
  889.             cursor.execute(sql, params)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/backends/utils.py" in execute
  79.             return super(CursorDebugWrapper, self).execute(sql, params)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/utils.py" in __exit__
  94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/utils/six.py" in reraise
  685.             raise value.with_traceback(tb)

File "/srv/modoboa/env/lib/python3.5/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /dashboard/
Exception Value: relation "msgrcpt" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "msgrcpt" WHERE "msgrcpt"....
                                          ^
```

**Comment by tonioo** [comment]
@ohid93 How did you install modoboa?

**Comment by ohid93** [comment]
I followed the official documentation instructions.
> git clone https://github.com/modoboa/modoboa-installer
> cd modoboa-installer
> sudo ./run.py <your domain>

**Comment by TildeSlashC0re** [comment]
it appears to me that your database wasn't initialized correctly... 

you have to run one of [these SQLs](https://github.com/modoboa/modoboa-installer/tree/master/modoboa_installer/scripts/files/amavis) on your amavis database.

Pick the corresponding SQL for the database-system(mysql/pgsql) you are using.

**Comment by bernd-wechner** [comment]
Hmmm, I used the installer too, and the amavis database exists, the user exists, and the tables were created using that script (they were missing, and I do wonder why it isn't handled with migrations, but that's another story) and I can see all that:

```
$ psql -h localhost modoboa-amavis amavis
Password for user amavis: 
psql (14.5 (Ubuntu 14.5-0ubuntu0.22.04.1), server 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

modoboa-amavis=> \dt
           List of relations
 Schema |    Name    | Type  |  Owner   
--------+------------+-------+----------
 public | maddr      | table | postgres
 public | mailaddr   | table | postgres
 public | msgrcpt    | table | postgres
 public | msgs       | table | postgres
 public | policy     | table | postgres
 public | quarantine | table | postgres
 public | users      | table | postgres
 public | wblist     | table | postgres
(8 rows)
modoboa-amavis=> select * from msgrcpt
modoboa-amavis-> \d msgrcpt
                                Table "public.msgrcpt"
    Column     |          Type          | Collation | Nullable |        Default        
---------------+------------------------+-----------+----------+-----------------------
 partition_tag | integer                |           | not null | 0
 mail_id       | bytea                  |           | not null | 
 rseqnum       | integer                |           | not null | 0
 rid           | integer                |           | not null | 
 is_local      | character(1)           |           | not null | ' '::bpchar
 content       | character(1)           |           | not null | ' '::bpchar
 ds            | character(1)           |           | not null | 
 rs            | character(1)           |           | not null | 
 bl            | character(1)           |           |          | ' '::bpchar
 wl            | character(1)           |           |          | ' '::bpchar
 bspam_level   | real                   |           |          | 
 smtp_resp     | character varying(255) |           |          | ''::character varying
Indexes:
    "msgrcpt_partition_mail_rseq" PRIMARY KEY, btree (partition_tag, mail_id, rseqnum)
    "msgrcpt_idx_mail_id" btree (mail_id)
    "msgrcpt_idx_rid" btree (rid)
    "msgrcpt_idx_rs" btree (rs)
modoboa-amavis-> 
```

and my settings include:

```python
AMAVIS_DEFAULT_DATABASE_ENCODING = 'utf8'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': 'localhost',
        'PORT': '',
        'NAME': 'modoboa',
        'USER': 'modoboa',
        'PASSWORD': 'modoboa_pass',
        'ATOMIC_REQUESTS': True,
    },
    "amavis": {
        "ENGINE" : "django.db.backends.postgresql",
        "HOST" : "localhost",
        'PORT': '',
        "NAME" : "modoboa-amavis",
        "USER" : "amavis",
        "PASSWORD" : "amavis_pass"
    }
}
```

The app is installed:

```python
MODOBOA_APPS = (
    'modoboa',
    'modoboa.core',
    'modoboa.lib',
    'modoboa.admin',
    'modoboa.transport',
    'modoboa.relaydomains',
    'modoboa.limits',
    'modoboa.parameters',
    'modoboa.dnstools',
    'modoboa.policyd',
    'modoboa.maillog',
    # Modoboa extensions here.
    'modoboa_webmail',
    'modoboa_contacts',
    'modoboa_automua',
    'modoboa_radicale',
    'modoboa_sievefilters',
    'modoboa_postfix_autoreply',
    'modoboa_pdfcredentials',
    'modoboa_amavis'
)
```

And here is the bomb:

```
Environment:


Request Method: GET
Request URL: https://hermes.thumbs.place/dashboard/

Django Version: 3.2.16
Python Version: 3.10.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'ckeditor',
 'ckeditor_uploader',
 'rest_framework',
 'rest_framework.authtoken',
 'drf_spectacular',
 'phonenumber_field',
 'django_otp',
 'django_otp.plugins.otp_totp',
 'django_otp.plugins.otp_static',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.admin',
 'modoboa.transport',
 'modoboa.relaydomains',
 'modoboa.limits',
 'modoboa.parameters',
 'modoboa.dnstools',
 'modoboa.policyd',
 'modoboa.maillog',
 'modoboa_webmail',
 'modoboa_contacts',
 'modoboa_automua',
 'modoboa_radicale',
 'modoboa_sievefilters',
 'modoboa_postfix_autoreply',
 'modoboa_pdfcredentials',
 'modoboa_amavis',
 'webpack_loader')
Installed Middleware:
('django_lighttpd_middleware.LighttpdMiddleware',
 'x_forwarded_for.middleware.XForwardedForMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'modoboa.core.middleware.TwoFAMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.core.middleware.LocalConfigMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware')



Traceback (most recent call last):
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (relation "msgrcpt" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "msgrcpt" WHERE "msgrcpt"....
                                          ^
) was the direct cause of the following exception:
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/template/context.py", line 244, in bind_template
    updates.update(processor(self.request))
  File "/data/venv/modoboa/lib/python3.10/site-packages/modoboa/core/context_processors.py", line 14, in top_notifications
    notifications = signals.get_top_notifications.send(
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/data/venv/modoboa/lib/python3.10/site-packages/modoboa_amavis/handlers.py", line 169, in check_for_pending_requests
    nbrequests = SQLconnector(user=request.user).get_pending_requests()
  File "/data/venv/modoboa/lib/python3.10/site-packages/modoboa_amavis/sql_connector.py", line 232, in get_pending_requests
    return Msgrcpt.objects.filter(rq).count()
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/models/query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/models/sql/query.py", line 528, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/models/sql/query.py", line 513, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/venv/modoboa/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /dashboard/
Exception Value: relation "msgrcpt" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "msgrcpt" WHERE "msgrcpt"....
```                                          ^

I wonder if @ohidxy still has this problem?
