### ISSUE TITLE
Impossible to execute management commands

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-amavis#24]
Since the migration to Django 1.8 and changes made to models, management commands cannot be run anymore. For example:
```python
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_amavis/management/commands/qcleanup.py", line 55, in handle
    if not msg.msgrcpt_set.exclude(rs__in=flags).count():
AttributeError: 'Msgs' object has no attribute 'msgrcpt_set'
```

**Comment by spinza** [comment]
Just checking when will 1.0.7 be released?  This bug is not a major problem but is annoying to get a daily cron email on it.

**Comment by tonioo** [comment]
It should be released within a few days.

**Comment by spinza** [comment]
tx

**Comment by spinza** [comment]
Still on 1.0.6.  Any timeline on 1.0.7?

Thanks!
