### ISSUE TITLE
"Table 'modoboa.users' doesn't exist" after "python manage.py load_initial_data"

### ISSUE THREAD

**Issue by controlcde** [modoboa/modoboa-amavis#29]
I´ve got an existing modoboa installation and I wan´t to add modoboa-amavis. I have done all the steps described on github page and on the last step `python manage.py load_initial_data` I´ve got an error
_"Table 'modoboa.users' doesn't exist"_. And I can´t get access to the web interface _"An internal error occurred."_ because of the missing amavis db tables.

Here is the complete output:
```
(modoboa-1.4.5)root@testmail:/srv/mailadmin# python manage.py load_initial_data
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/modoboa/core/management/commands/load_initial_data.py", line 64, in handle
    extension.load_initial_data()
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/modoboa_amavis/modo_extension.py", line 42, in load_initial_data
    policy = create_user_and_policy("@{0}".format(dom.name))
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/modoboa_amavis/lib.py", line 242, in create_user_and_policy
    if Users.objects.filter(email=name).exists():
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/db/models/query.py", line 586, in exists
    return self.query.has_results(using=self.db)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 484, in has_results
    return compiler.has_results()
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 811, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/srv/venv/modoboa-1.4.5/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'modoboa.users' doesn't exist")
```

**Comment by controlcde** [comment]
After deleting instance dir and reinstalling modoboa instance with the amavis extension (without deleting the database) everything is alright.

**Comment by tonioo** [comment]
You need to add the following line at the end of your settings.py file:

```python
from modoboa_amavis.settings import *
```

**Comment by controlcde** [comment]
Ok, thanks @tonioo. This information should be in the [Readme](https://github.com/modoboa/modoboa-amavis/blob/master/README.rst).
