### ISSUE TITLE
modoboa-amavis AttributeError

### ISSUE THREAD

**Issue by dasbaumwolltier** [modoboa/modoboa-amavis#97]
I recently reinstalled modoboa. After trying to install modoboa-amavis I got this error, when I try to run 
```bash
python manage.py migrate
```
or anything else from modoboa:  

```text
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/modoboa_amavis/apps.py", line 19, in ready
    from . import handlers  # noqa:F401
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/modoboa_amavis/handlers.py", line 19, in <module>
    from .lib import (
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/modoboa_amavis/lib.py", line 30, in <module>
    from .utils import smart_bytes, smart_text
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/modoboa_amavis/utils.py", line 64, in <module>
    class ConvertFrom(Func):
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/modoboa_amavis/utils.py", line 75, in ConvertFrom
    settings.AMAVIS_DEFAULT_DATABASE_ENCODING)
  File "/opt/modoboa/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'AMAVIS_DEFAULT_DATABASE_ENCODING'
```

I hope I did not overlook something, but I thing I tried everything described in the manual.
Thanks in advance for your help

**Comment by florealcab** [comment]
Do you add this in settings.py ?

from modoboa_amavis import settings as modoboa_amavis_settings
modoboa_amavis_settings.apply(globals())

**Comment by dasbaumwolltier** [comment]
Strange... I don't remember this to be a part of the installation instructions.
Anyway, thanks for the help, now it works.
